version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-neobot}
      POSTGRES_USER: \${POSTGRES_USER:-neobot}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
