#!/bin/bash
# 🚀 INSTRUCTIONS RAPIDES - SYSTÈME INTELLIGENT WHATSAPP V3.0
# Votre nouveau système est PRÊT! Voici exactement quoi faire.

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  🎉 SYSTÈME INTELLIGENT WHATSAPP V3.0 - DÉMARRAGE RAPIDE   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ LIVRAISON COMPLÈTE:"
echo "  • Nouveau système intelligent = whatsapp-service/index.js"
echo "  • Documentation = WHATSAPP_INTELLIGENT_SYSTEM.md"
echo "  • Guide rapide = DEMARRAGE_RAPIDE_INTELLIGENT.md"
echo "  • Script de test = test_intelligent_system.sh"
echo "  • Résumé final = LIVRAISON_FINALE.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 3 ÉTAPES POUR UTILISER LE SYSTÈME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📌 ÉTAPE 1: DÉMARRER LE SERVICE"
echo "  cd /home/tim/neobot-mvp/whatsapp-service"
echo "  npm start"
echo ""
echo "  ➜ Vous verrez un code QR à scanner"
echo "  ➜ Suivez les instructions affichées (en français)"
echo ""

echo "📌 ÉTAPE 2: SCANNER LE CODE QR"
echo "  Prenez votre téléphone et:"
echo "    1. Ouvrez WhatsApp"
echo "    2. Allez dans: Paramètres → Appareils connectés"
echo "    3. Cliquez sur 'Connecter un appareil'"
echo "    4. Scannez le code QR (valide 60 secondes)"
echo ""

echo "📌 ÉTAPE 3: VÉRIFIER QUE ÇA MARCHE"
echo "  Dans un autre terminal, lancez:"
echo "  bash /home/tim/neobot-mvp/test_intelligent_system.sh"
echo ""
echo "  ➜ Vous verrez: '✅ TOUS LES TESTS RÉUSSIS!'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 🆕 CE QUI EST NOUVEAU"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Système Intelligent:"
echo "  • 6 états de connexion (initializing → connected → disconnected)"
echo "  • Détecte pourquoi vous êtes déconnecté"
echo "  • Messages clairs en français"
echo "  • Rescanne automatique si la session expire"
echo "  • 5 new APIs pour monitoring"
echo "  • Logs détaillés avec timestamps"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 🔧 VÉRIFIER L'ÉTAT QUAND VOUS VOULEZ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Connexion simple (oui/non):"
echo "  curl http://localhost:3001/health"
echo ""
echo "Détails complets:"
echo "  curl http://localhost:3001/api/whatsapp/status"
echo ""
echo "Y a-t-il un QR à scanner?:"
echo "  curl http://localhost:3001/api/whatsapp/qr-status"
echo ""
echo "Redémarrer le service manuellement:"
echo "  curl -X POST http://localhost:3001/api/whatsapp/restart"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Pour les IMPATIENTS (5 min):"
echo "  cat /home/tim/neobot-mvp/DEMARRAGE_RAPIDE_INTELLIGENT.md"
echo ""
echo "Pour comprendre TOUT (30 min):"
echo "  cat /home/tim/neobot-mvp/WHATSAPP_INTELLIGENT_SYSTEM.md"
echo ""
echo "Pour voir la LIVRAISON COMPLÈTE:"
echo "  cat /home/tim/neobot-mvp/LIVRAISON_FINALE.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 📊 VOIR LES LOGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "En temps réel:"
echo "  tail -f /home/tim/neobot-mvp/whatsapp-service/logs/whatsapp.log"
echo ""
echo "Les 50 dernières lignes:"
echo "  tail -50 /home/tim/neobot-mvp/whatsapp-service/logs/whatsapp.log"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 C'EST PRÊT! Lancez maintenant:"
echo ""
echo "   cd /home/tim/neobot-mvp/whatsapp-service"
echo "   npm start"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
