[pytest]
testpaths = tests
asyncio_mode = auto
# Affiche les print() pendant les tests pour faciliter le debug
log_cli = true
log_cli_level = WARNING
# Masque les warnings non actionnables
filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::DeprecationWarning:passlib.*
